### ISSUE TITLE
Ravager WASD movement and rotation weird

### ISSUE THREAD

**Issue by BillyGalbreath** [PurpurMC/Purpur#29] opened 2020-06-20 00:00 UTC
When riding a ravager the movement and rotations are weird.

The most noticable thing is the rotation while moving snaps and locks to what seems to be an arbitrary rotation. Ejecting and remounting sometimes moves this rotation to lock somewhere else.

Other odd behavior is when moving, sometimes the ravager just stops. You have to let go of the key and repress for it to continue moving if it doesn't on its own.

Also seems to not like walking down blocks. It seems to stop for a moment before walking over the edge.

Also if you hold spacebar while moving the speed becomes unstable, sometimes shooting you many blocks away very fast.

Can't seem to figure this one out :/ If anyone has any ideas or has seen another project/plugin fix this, let me know.

**Comment by UserDerezzed** [comment] 2020-10-09 18:58
Good to see that I'm not the only one with this issue.

I believe I spoke to you previously about this issue, and how it affects one of my private plugins - AvatarCreatures. I personally haven't found a fix to this issue either. The bugs I'm experiencing are exactly what you describe here - however, with some testing, I believe that the rotation that it snaps to while moving is related to the NPC's last movement destination.

**Comment by Aztlon** [comment] 2021-02-08 17:43
Just found this bug as well. As @relavis noted, it seems like the direction the ravager is facing is the last angle they were facing when they were mounted. The ravager follows the player's yaw if they're not moving, so the problem is just with movement.

**Comment by cardanawandra** [comment] 2021-07-01 05:01
it's not problem in server, it's client bug

if you see someone riding ravager, it's ok for other player, but not for them pov

**Comment by IllagerCaptain** [comment] 2023-03-19 00:45
Has this been fixed with the new `/ride` command in 1.19.4?

**Comment by 1ByteBit** [comment] 2023-03-19 01:00
You're unable to move mobs with the vanilla `/ride` command, if that's what you're asking

**Comment by granny** [comment] 2023-03-19 01:04
> You're unable to move mobs with the vanilla `/ride` command, if that's what you're asking

There were a ton of client-side bugs that were fixed since mojang made it easier for end-users to ride mobs. The hope is that along with those fixes, they also fixed this weird rotation bug as well.

We have yet to determine if that's the case, though. Still have some things to fix and look into

**Comment by granny** [comment] 2024-04-30 03:52
On a whim I thought I'd see if this was fixed in the update to 1.20.5/1.20.6 (Last time I tested it was around 1.19.3/1.19.4).

https://github.com/PurpurMC/Purpur/assets/43185817/39ff295f-8cbd-45c8-a0ba-c002690366bf

It has \o/ Thank you Mojang

**Closed by granny** 2024-04-30 03:52 UTC
Labels: bug, help wanted
